version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
      - TZ=${TZ}
    expose:
      - "5001"
    volumes:
      - ./app:/var/www/app

  nginx:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "81:80"
